# Generated by Django 6.0.6 on 2026-06-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizador',
            name='correo',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
